name: Deploy (admin)
on:
  push:
    branches: [main]

concurrency:
  group: "pages-admin"
  cancel-in-progress: true

jobs:
  deploy:
    if: "contains(github.event.head_commit.message, '[admin]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v4
